#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["src/Budgetr.Server/Budgetr.Server.csproj", "src/Budgetr.Server/"]
COPY ["src/Budgetr.Class/Budgetr.Class.csproj", "src/Budgetr.Class/"]
COPY ["src/Budgetr.DataAccess/Budgetr.DataAccess.csproj", "src/Budgetr.DataAccess/"]
COPY ["src/Budgetr.Logic/Budgetr.Logic.csproj", "src/Budgetr.Logic/"]
COPY ["src/Budgetr.Shared/Budgetr.Shared.csproj", "src/Budgetr.Shared/"]
RUN dotnet restore "src/Budgetr.Server/Budgetr.Server.csproj"
COPY . .
WORKDIR "/src/src/Budgetr.Server"
RUN dotnet build "Budgetr.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Budgetr.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Budgetr.Server.dll"]